backend:
  name: git-gateway
  branch: main

site_url: https://keen-mousse-ba761c.netlify.app

media_folder: "images"
public_folder: "/images"

collections:
  - name: "products"
    label: "প্রোডাক্টস"
    folder: "products"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "শার্টের নাম", name: "title", widget: "string"}
      - {label: "দাম (টাকা)", name: "price", widget: "number"}
      - {label: "পুরাতন দাম", name: "old_price", widget: "number"}
      - {label: "সাইজ", name: "size", widget: "string", default: "L, XL"}
      - {label: "ছবি", name: "image", widget: "image"}
